-- psql -U dunder_mifflin -d noteful -f ./migrations/001.do.create_noteful_tables.sql

CREATE TABLE folders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);

CREATE TABLE notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    folderId INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    modified TIMESTAMP DEFAULT now() NOT null
);